### ISSUE TITLE
onPreResponse doesn't invoke in hapi 17.5.5

### ISSUE THREAD

**Issue by venikman** [fs-opensource/hapi-dev-errors#5]
I wrote a test which passing on `hapi: 17.5.4` but failing on `hapi: 17.5.5`. Difference that when your response schema failing and on request, you don't specify headers in `17.5.4` `onPreResponse` doesn't invoke. Server will response with `json` but in `17.5.5` it invokes `onPreResponse`.
This is branch with new test: https://github.com/venikman/hapi-dev-errors/blob/master/test/failed-response-schema.js

**Comment by marcuspoehls** [comment]
@venikman Hi Stan, do you expect a JSON response as the default? Because there’s no `accept` header that matches `json`, the response is HTML.

**Comment by marcuspoehls** [comment]
@venikman I’ve checked the recent hapi changes and it seems like the previous handling was a bug.

The response before `hapi 17.5.4` added the `application/json` request header, even though it wasn’t on the request originally.

With `hapi 17.5.5`, this changed and `hapi-dev-errors` responds with HTML because the request doesn’t want JSON explicitly.

**Comment by venikman** [comment]
@marcuspoehls  So you think right now it response right way?

**Comment by marcuspoehls** [comment]
@venikman Yeah, I think the behavior of `hapi-dev-errors` is correct for hapi `17.5.5`.

**Comment by marcuspoehls** [comment]
Yes please, I really appreciate a PR to add this test. That's a great idea, thank you!

Can you please add a second test that makes sure JSON response is sent for requests that want JSON (set the accept header to application/JSON).

**Comment by venikman** [comment]
Sure! No problem.
